services:
  database-dev:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_UNAME}
      - POSTGRES_PASSWORD=${DB_PSWD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - PGHOST=${DB_HOST}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - 5432:5432
    
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_UNAME}
      - POSTGRES_PASSWORD=${DB_PSWD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - PGHOST=${DB_HOST}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      cims-internal:
        aliases:
          - cims-database

  backend:
    image: bikramghuku05/cims-backend:latest
    build: ./backend
    restart: unless-stopped
    environment:
      - DB_UNAME=${DB_UNAME}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=cims-database
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      cims-internal:
        aliases:
          - cims-backend
    ports:
      - ${PORT}:${PORT}
    
    depends_on:
      - database

  frontend:
    image: bikramghuku05/cims-frontend:latest
    restart: unless-stopped
    networks:
      cims-internal:
        aliases:
          - cims-frontend
    ports:
      - 8443:80
    depends_on:
      - backend

  backup:
    image: bikramghuku05/psql-dbox:latest
    restart: unless
    environment:
      - DB_UNAME=${DB_UNAME}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=cims-database
      - DB_PORT=${DB_PORT}
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
    networks:
      cims-internal:
        aliases:
          - cims-bckup

    depends_on:
      - database

networks:
  cims-internal:
