import React, { useRef } from 'react';
import Invoice from '../components/Invoice'; // Adjust the path if necessary

export const sampleData = [
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    }, {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
    {
        id: '1',
        item_used: 2,
        user_id: 'u1',
        username: 'John Doe',
        role: 'Worker',
        item_id: 'i1',
        item_name: 'Item A',
        item_qty: 100,
        item_price: 50,
        item_desc: 'Description for Item A',
        comp_id: 'c1',
        comp_nos: '123',
        comp_loc: 'Location A',
        comp_des: 'Description for Complaint A',
        comp_stat: 'Open',
        comp_date: '2024-07-01',
    },
];

const InvoicePage: React.FC = () => {
    const invoiceRef = useRef<HTMLDivElement>(null);
    

    return (
        <div>
            <h1>Invoice Page</h1>
            <Invoice ref={invoiceRef} selectedItems={sampleData} />
        </div>
    );
};

export default InvoicePage;
